language: node_js
node_js: node #latest stable version

before_script:
- chmod +x test-ci.sh
- yarn build
- openssl aes-256-cbc -K $encrypted_cc828242bf9e_key -iv $encrypted_cc828242bf9e_iv -in ci-key.json.enc -out ci-key.json -d
- cd test && yarn install
- cd ..

script: yarn run test:ci
