language: node_js
node_js: 10

before_script:
- chmod +x test-ci.sh
- yarn build
- openssl aes-256-cbc -K $encrypted_cc828242bf9e_key -iv $encrypted_cc828242bf9e_iv -in ci-key.json.enc -out ci-key.json -d
- cd test && yarn install
- cd ..

script: yarn run test:ci

deploy:
  provider: heroku
  api_key:
    secure: VGYG/BIEaWY4/nTgMu2qMArWLYTe1Bx8IYC2oj8fw6X31li+GU5ZhKeFFkj7eoS7K9iOtLTnk64mnbsoTAmD7h0kRRu6uW22JEdpQvYD7EUv25nWI7pM1C13whpP7am8rwU0lsk6Crc6PTauBAzSbPRyl2VBtwD9gnhR06uICGEJCLmefpr6sy6pigjS58gNZXq/3311ObIKRq5J2ZWMvrqqNMBdO0cLLZS9XyxevcJNbTZiVTY3IAT9rxZQegY5gltOiKCnyUlgqN/QpK3FpB1bH4AyZx9QlVCMaYsSKdEnLJ0mteq0f1EcIDbIY1j3e29L4DIzjjudJCrfVnP7GZv3HGSFDi+7CyjfiDRjgYD57IVDdso91y/qdghj03orako4MsiYJAdVJwl2dyVKPi/78YcveUJDMGZJCHoEVh+rTwcRmU3AVo+ueR4QiSdOT6LinS6f7G1feStKjnFv/rseyGG/pcIl6M7DUJIChnnIpNQnZAJQazdVnbd5RoO3fK4UK81kqcovInm46hiRdrD+HHplLVLwKfm8sf8YmQv0EneUM7PjUumx/ziy5CDfyooJWsCFQk61AQ8SjJrZcwgdJEqcOoPiNyJfhTQDwaPiUoc195HHd/IPkCMDEe754BC/WqX4IFp7RzjL3h76WDaReSeUXMC4d4vSogBrTZM=
