language: node_js
node_js: 10

before_script:
- chmod +x test-ci.sh
- yarn build
- openssl aes-256-cbc -K $encrypted_cc828242bf9e_key -iv $encrypted_cc828242bf9e_iv -in ci-key.json.enc -out ci-key.json -d
- cd test && yarn install
- cd ..

script: yarn run test:ci

deploy:
  provider: heroku
  api_key:
    secure: B8mwLCWe1On2H/fXFqysbIbhE6GJyP7kxqbyQyeiDXdulIrFC8BcsWB9Y8DayXZiGZGzq6RJILNhNlw5/3A+FrgK477K1bSHT5gZaGIo2z6lAvB71Xwdz9qSXIgvvRu0N1L1TRPI8posKyrI9X+hoWbkVYt+UEY3wX5/qK87X1BcCxeEU843cVZ9QQQ+7OuvpIwVJypmswkGX+fkESe+QNN23FTz/vSSyJKlVmg5sQHJ27wO4EkjiwsCtwLWWDcSwM2MJwxwmM26Y/n3Pa4c2tKRvTvn4D+C8QGLP5DydY/L8xNe0Y9rgSH9qjEENLJl2uEsNdrGekXXFxdUhsVErExFpG4+yy1xeZ9EdPXwvxH2BB7MjvxQIRVCewDU67ss3HU4innFN03NgcwZKuaue4soH+O8I8yceau0aEwmWzVNViPstJ2enSYU8sZhUH3wZInz58/dBPj4z1oUsD/mZJV5yFrdSvTsfDbCFWOWN5DtFEbq6HLSBHezwpn8QsbDxZG7zRRjPIqc410ca7K1RLySIalQCw05HZDBKsW4jJ9wpgxkb8Z6Y9oRcXoMADo0woIRZK5kZH1dwqih7j+Ky09CjvjAXR7/BijRjmqR0z2t3NyeY6dq7pTe8JyQGDCAcY1k5jPH07aORIBZEMkWLKUV6Aux850lC7kPCtwPXL0=
